# Generated by Django 3.2.13 on 2022-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noadult',
            field=models.CharField(choices=[('F', 'false'), ('T', 'true')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='nofear',
            field=models.CharField(choices=[('F', 'false'), ('T', 'true')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=0),
        ),
    ]
