# Generated by Django 3.2.13 on 2022-11-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221120_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='noadult',
            new_name='nothrill',
        ),
    ]
